apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: document-download-api 
  name:  document-download-api
  namespace: notification-canada-ca
spec:
  selector:
    matchLabels:
      app: document-download-api 
  template:
    metadata:
      labels:
        app: document-download-api
    spec:
      containers:
        - image: document-download-api
          imagePullPolicy: Always
          name: document-download-api 
          env:
            - name: DEBUG
              value: 'False'
            - name: FRONTEND_HOSTNAME
              value: 'document.$(BASE_DOMAIN)'
            - name: HTTP_SCHEME
              value: 'https'
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
