apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: document-download-frontend
  name:  document-download-frontend
  namespace: notification-canada-ca
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: document-download-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: document-download-frontend
    spec:
      containers:
        - image: document-download-frontend
          imagePullPolicy: Always
          name: document-download-frontend
          env:
            - name: DEBUG
              value: 'False'
            - name: ADMIN_BASE_URL
              value: https://$(BASE_DOMAIN)
            - name: API_HOST_NAME
              value: http://api.notification-canada-ca.svc.cluster.local:6011
            - name: DOCUMENT_DOWNLOAD_API_HOST_NAME
              value: 'https://api.$(BASE_DOMAIN)'
            - name: PORT
              value: '7001'
            - name: HTTP_PROTOCOL
              value: 'https'
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
