apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: traefik-ingress
  namespace: notification-canada-ca
spec:
  rules:
    - host: $(BASE_DOMAIN)
      http:
        paths:
          - path: /
            backend:
              serviceName: admin
              servicePort: 6012
    - host: api.$(BASE_DOMAIN)
      http: 
        paths:         
          - path: /
            backend:
              serviceName: api
              servicePort: 6011
    - host: document.$(BASE_DOMAIN)
      http: 
        paths:         
          - path: /
            backend:
              serviceName: document-download-frontend
              servicePort: 7001
    - host: api.document.$(BASE_DOMAIN)
      http: 
        paths:         
          - path: /
            backend:
              serviceName: document-download-api
              servicePort: 7000