apiVersion: v1
kind: Service
metadata:
  labels:
    name: bastion
  name: bastion
  namespace: notification-canada-ca
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: bastion
  selector:
    app: bastion
