apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
  labels:
    io.kompose.service: bastion-claim
  name: bastion-claim
  namespace: notification-canada-ca
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi