bases:
  - ../../base

resources:
  - storage-class-default.yaml
  - certs-claim.yaml
  - bastion-claim.yaml
  - bastion-deployment.yaml
  - bastion-service.yaml
  - traefik-ingress-service.yaml
  - traefik-ingress-controller-deployment.yaml
  - traefik-ingress-service-ds.yaml
  - traefik-ingress-controller-ds.yaml
  - fluentd.yaml
  - cwagent-statsd-configmap.yaml
  - cwagent-statsd-deployment.yaml
  # - celery-deployment-fargate.yaml
  - aggregated-metrics-reader.yaml
  - auth-delegator.yaml
  - auth-reader.yaml
  - metrics-apiservice.yaml
  - metrics-server-deployment.yaml
  - metrics-server-service.yaml
  - resource-reader.yaml


images:
- name: admin
  newName: gcr.io/cdssnc/notify/admin:6db02b4
- name: api
  newName: gcr.io/cdssnc/notify/api:d7abaa7
- name: document-download-api
  newName: gcr.io/cdssnc/notify/document-download-api:latest
- name: document-download-frontend
  newName: gcr.io/cdssnc/notify/document-download-frontend:latest
- name: bastion
  newName: gcr.io/cdssnc/notify/bastion:latest

configMapGenerator:
- name: application-config
  env: .env

vars:
  - name: BASE_DOMAIN
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.BASE_DOMAIN
  - name: ENVIRONMENT
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ENVIRONMENT
  - name: POSTGRES_SQL
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.POSTGRES_SQL
  - name: POSTGRES_HOST
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.POSTGRES_HOST
  - name: HASURA_ACCESS_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.HASURA_ACCESS_KEY
  - name: HASURA_JWT_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.HASURA_JWT_KEY
  - name: BASTION_SLACK_URL
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.BASTION_SLACK_URL
  - name: AWS_REGION
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_REGION
  - name: AWS_ACCESS_KEY_ID
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_SECRET_ACCESS_KEY
  - name: ADMIN_CLIENT_SECRET
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ADMIN_CLIENT_SECRET
  - name: SECRET_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.SECRET_KEY
  - name: DANGEROUS_SALT
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.DANGEROUS_SALT
  - name: MLWR_HOST
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.MLWR_HOST
  - name: MLWR_USER
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.MLWR_USER
  - name: MLWR_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.MLWR_KEY
  - name: TWILIO_ACCOUNT_SID
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.TWILIO_ACCOUNT_SID
  - name: TWILIO_AUTH_TOKEN
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.TWILIO_AUTH_TOKEN
  - name: TWILIO_FROM_NUMBER
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.TWILIO_FROM_NUMBER
  - name: SENDGRID_API_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.SENDGRID_API_KEY
  - name: ADMIN_CLIENT_USER_NAME
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ADMIN_CLIENT_USER_NAME
  - name: AUTH_TOKENS
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AUTH_TOKENS
  - name: DOCUMENTS_BUCKET
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.DOCUMENTS_BUCKET
  - name: AWS_ROUTE53_ZONE
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_ROUTE53_ZONE
  - name: AWS_SES_REGION
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_SES_REGION
  - name: AWS_SES_SMTP
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_SES_SMTP
  - name: AWS_SES_ACCESS_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_SES_ACCESS_KEY
  - name: AWS_SES_SECRET_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.AWS_SES_SECRET_KEY
  - name: FRESH_DESK_API_URL
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.FRESH_DESK_API_URL
  - name: FRESH_DESK_API_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.FRESH_DESK_API_KEY
