resources:
  - ../../base
  - storage-class-default.yaml
  - certs-claim.yaml
  - bastion-claim.yaml
  - bastion-deployment.yaml
  - bastion-service.yaml
  - traefik-ingress-service.yaml
  - traefik-ingress-controller-deployment.yaml
  - fluentd.yaml
  - cwagent-statsd-configmap.yaml
  - cwagent-statsd-deployment.yaml


images:
- name: admin
  newName: 691098801562.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/admin:latest	
- name: api
  newName: 691098801562.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/api:latest
- name: document-download-api
  newName: 691098801562.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/document-download-api:latest
- name: document-download-frontend
  newName: 691098801562.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/document-download-frontend:latest
- name: bastion
  newName: 691098801562.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/bastion:latest

configMapGenerator:
- name: application-config
  env: .env

vars:
  - name: BASE_DOMAIN
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.BASE_DOMAIN
  - name: ENVIRONMENT
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.ENVIRONMENT
  - name: POSTGRES_SQL
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.POSTGRES_SQL
  - name: POSTGRES_HOST
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.POSTGRES_HOST
  - name: HASURA_ACCESS_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.HASURA_ACCESS_KEY
  - name: HASURA_JWT_KEY
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.HASURA_JWT_KEY
  - name: BASTION_SLACK_URL
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.BASTION_SLACK_URL