resources:
  - ../../base
  - storage-class-default.yaml
  - config-map.yaml
  - certs-claim.yaml
  - traefik-ingress-service.yaml
  - traefik-ingress-controller-deployment.yaml
patches:
  - postgres-claim.yaml

images:
- name: admin
  newName: 241785157803.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/admin:a5e1c2c2033359834d24614aa482b202c9a5d651
- name: api
  newName: 241785157803.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/api:0e6c4b229aaeb8bd35e36d1758b6c16d1d152f76
- name: document-download-api
  newName: 241785157803.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/document-download-api:9fb0b24da6e6a9870254e2a9639901a1d351dfd8
- name: document-download-frontend
  newName: 241785157803.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/document-download-frontend:7bc9b3175ba9aa34531bd74714d856620dda760f
- name: statsd
  newName: 241785157803.dkr.ecr.us-east-1.amazonaws.com/notification-canada-ca/statsd:latest

vars:
  - name: BASE_DOMAIN
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.base_domain
  - name: ENVIRONMENT
    objref:
      kind: ConfigMap
      name: application-config
      apiVersion: v1
    fieldref:
      fieldpath: data.environment