apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2
  name: postgres-claim
  namespace: notification-canada-ca
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
