apiVersion: v1
kind: Service
metadata:
  name: traefik-ds
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      name: http
      nodePort: 30080
      port: 80
  selector:
    app: traefik-ds
  type: NodePort
