kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.0
          args:
            - --api=false
            - --accesslog
            - --entrypoints.http.Address=:80
            - --entryPoints.http.proxyProtocol.insecure
            - --entryPoints.http.forwardedHeaders.insecure
            - --entrypoints.bastion.Address=:3419
            - --providers.kubernetescrd
            - --accesslog.format=json
            - --accesslog=true
            - --log=true
          ports:
            - containerPort: 80
              name: http
            - containerPort: 3419
              name: bastion
          securityContext:
            capabilities:
              add:
              - NET_BIND_SERVICE
              drop:
              - ALL
      terminationGracePeriodSeconds: 60