apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      name: bastion
      nodePort: 33419
      port: 3419
    - protocol: TCP
      name: http
      nodePort: 30080
      port: 80
  selector:
    app: traefik
  type: NodePort
