name: Build and deploy to master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: AWS Decrypt
        uses: docker://gcr.io/cdssnc/aws:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          entrypoint: sh
          args: -l -c "cd manifests/overlays/eks && aws kms decrypt --ciphertext-blob fileb://.env.enc.aws --output text --query Plaintext --region us-east-1 | base64 --decode > .env"
      - name: EKS
        uses: docker://gcr.io/cdssnc/aws:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: eks --region us-east-1 update-kubeconfig --name notification-alpha-canada-ca

      - name: Apply Configuration
        uses: docker://gcr.io/cdssnc/aws-kubectl:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: apply --kubeconfig=/github/home/.kube/config -k manifests/overlays/eks
      - name: Add deployment to New Relic
        run: |
          for application_id in 283469061 283468826 283468685; do
            curl -X POST "https://api.newrelic.com/v2/applications/$application_id/deployments.json" \
             -H "X-Api-Key:$NEW_RELIC_API_KEY" -i \
             -H 'Content-Type: application/json' \
             -d \
            '{
              "deployment": {
                "revision": "$GITHUB_SHA"
              }
            }'
          done
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
